- Makefile
- application/app/services/detach_process.rb
- application/app/services/download/download_files_provider.rb
- application/app/services/download/download_service.rb
- application/test/utils/download_files_provider_mock.rb
Fixed execution of download process so that it does not stop when parent stops in OOD.
I have to revert to the initial solution as the previous one does not work in the OOD environment.
> Fixed execution of download process 

- application/app/controllers/dataverse/datasets_controller.rb
- application/app/controllers/dataverse/dataverses_controller.rb
- application/app/services/dataverse/dataverse_service.rb
- application/test/controllers/dataverse/datasets_controller_test.rb
- application/test/controllers/dataverse/dataverses_controller_test.rb
It happens to be that the search endpoint used to display a dataverse content, in some installations requires authentication and doesn't allow access for public resources. In these scenarios, the endpoint returns a status code 401. In this PR we handle this restriction to redirect the user with a message
> handle Unauthorized endpoint exception

- Makefile
- application/app/services/common/http_client.rb
The problems seems to be that `hub.dataverse.org ` SSL cert is not configured correctly and not returning the full chain of trusted certs. So we have to add the final certificate as a trusted one in the container.
I created a new version of our container with these certs and uploaded it to DockerHub:
`hmdc/sid-ood:ood-3.1.7.ssl.el8`
> Fixed SSL cert issue with hub.dataverse.org

- application/app/models/dataverse/create_dataset_request.rb
- application/app/models/dataverse/create_dataset_response.rb
- application/app/services/dataverse/dataset_service.rb
- application/test/fixtures/dataverse/create_dataset_response/valid_response.json
- application/test/models/dataverse/create_dataset_response.rb
Sample usage code:
```ruby
def test_create
@dataverse_url = "https://demo.dataverse.org/"
@service = Dataverse::DataverseService.new(@dataverse_url)
@citation_metadata = @service.get_citation_metadata
@body = Dataverse::CreateDatasetRequest.new title: "test service", author: "David",  description: "Lorem ipsum",
contact_email: "david@example.com", subjects: [@citation_metadata.subjects.first]
@dataset_service = Dataverse::DatasetService.new(@dataverse_url, api_key: "<api_key>")
@response = @dataset_service.create_dataset(":root", @body)
render :inline => @response.persistent_id
end
```
> Create dataset service

- application/app/connectors/dataverse/actions/collection_select.rb
- application/app/connectors/dataverse/actions/connector_edit.rb
- application/app/connectors/dataverse/actions/dataset_create.rb
- application/app/connectors/dataverse/actions/dataset_select.rb
- application/app/connectors/dataverse/upload_batch_connector_metadata.rb
- application/app/connectors/dataverse/upload_batch_connector_processor.rb
- application/app/controllers/upload_batches_controller.rb
- application/app/javascript/controllers/utils/tab_links_controller.js
- application/app/services/dataverse/concerns/dataverse_url_builder.rb
- application/app/services/dataverse/dataverse_url.rb
- application/app/views/connectors/dataverse/_upload_batch_actions_bar.html.erb
- application/app/views/connectors/dataverse/_upload_batch_info_bar.html.erb
- application/app/views/projects/_project_summary.html.erb
- application/app/views/projects/_upload_batch.html.erb
- application/app/views/projects/show.html.erb
- application/app/views/projects/show/_download_files.html.erb
- application/app/views/projects/show/_project_actions.html.erb
- application/app/views/projects/show/_project_tabs.html.erb
- application/app/views/projects/show/_upload_actions.html.erb
- application/app/views/projects/show/_upload_batch.html.erb
- application/app/views/upload_status/_files.html.erb
- application/config/locales/views/en.yml
- application/test/services/dataverse/concerns/dataverse_url_builder.rb
Minor UI improvements.
Added links to the Dataverse, Collection and Dataset on UploadCollections.
Added support to link directly to the content of a tab.
To check the new behaviour:
- Select a collection
- Select a dataset
- Create a dataset
- Add/update API key
In all these cases, the active tab should be open again.
> Added support to link directly to tab content

- application/app/controllers/zenodo/landing_page_controller.rb
- application/app/helpers/zenodo/landing_page_helper.rb
- application/app/models/zenodo/record_response.rb
- application/app/models/zenodo/search_response.rb
- application/app/views/zenodo/landing_page/index.html.erb
- application/app/views/zenodo/records/show.html.erb
- application/config/locales/connectors/zenodo/en.yml
- application/test/controllers/zenodo/landing_page_controller_test.rb
- application/test/fixtures/zenodo/record_response.json
- application/test/fixtures/zenodo/search_response.json
- application/test/helpers/zenodo/landing_page_helper_test.rb
- application/test/models/zenodo/record_response_test.rb
- application/test/models/zenodo/search_response_test.rb
The Zenodo search functionality lacked pagination and was only showing the first 10 results.
This PR adds pagination as with Dataverse.
Fixes: #218
> Add pagination support to Zenodo landing page

- application/app/views/upload_status/_files.html.erb
Fix to the badge size after the refactoring to use the new DV logo
> fix: Fixed upload badge repo size

- application/app/services/dataverse/dataverse_url.rb
- application/test/services/dataverse/dataverse_url_test.rb
Add support for citation URLs from dataverse.
Fixes bug: #254 
When I click on Explore
And I enter doi:10.60507/FK2/65F6H4
And I click on Connect
Then I'm redirected to https://localhost:33000/pun/sys/loop/view/repo/resolve
And the error Cannot redirect to nil! is displayed
> feat: Add support for Dataverse  citation URLs

- application/app/lib/logging_common.rb
- application/app/services/dataverse/dataverse_restrictions_service.rb
- application/app/services/download/basic_http_ruby_downloader.rb
- application/app/views/dataverse/datasets/_dataset_file_row.html.erb
- application/app/views/dataverse/datasets/_dataset_files.html.erb
- application/app/views/dataverse/datasets/show.html.erb
- application/config/locales/connectors/dataverse/en.yml
- application/test/services/dataverse/dataverse_restrictions_service_test.rb
Fixed UI for restricted files. This was broken as it was using FA icons
> fix: Fixed dataset file restrictions UI

- application/app/helpers/application_helper.rb
- application/app/views/dataverse/datasets/_dataset_files.html.erb
- application/app/views/zenodo/records/_record_files.html.erb
- application/config/locales/connectors/dataverse/en.yml
- application/config/locales/connectors/zenodo/en.yml
- application/test/controllers/dataverse/datasets_controller_test.rb
- application/test/controllers/zenodo/records_controller_test.rb
- show different text for download submit buttons based on active project
- add translations for new and active project labels
- add tests for button text in dataset and record views
Fixes: https://github.com/IQSS/ondemand-loop/issues/311
- Update views
- Update translations
- Add tests
> feat: Download button should consider the presence of Active projects

- docs/guide/content/user_guide/downloading_files.md
- docs/guide/content/user_guide/finding_data.md
- docs/guide/content/user_guide/index.md
- docs/guide/content/user_guide/projects.md
- docs/guide/content/user_guide/uploading_files.md
This PR address the review suggestions provided by Bill:
- In the User Guide:
- Introduction page:
- It says that the Working directory keeps files "isolated." I think this term is too strong and inaccurate since the files are not in isolation but are grouped into projects. I suggest changing this to "separated."
- It says that each "upload and download action is a discrete, immutable operation." I suggest removing the word "immutable" as a descriptor of upload and download operations since it is not accurate. An upload or download operation can be mutated through cancellation, and I think the mention of mutability distracts from the point that files are not synchronized.
- It describes the spatial layout of the top navigation elements. However, the description is not correct. The …
> Doc user guide review

- application/app/services/dataverse/dataverse_hub.rb
- application/test/services/dataverse/dataverse_hub_test.rb
Update DataverseHub URL as the server has chaged
Fixes #305 
- DataverseHub URL update
> fix: Updated DataverseHub URL after server update

- application/app/connectors/dataverse/explore_connector_processor.rb
- application/app/connectors/zenodo/explore_connector_processor.rb
- application/app/controllers/explore_controller.rb
- application/config/locales/connectors/zenodo/en.yml
- application/config/locales/controllers/en.yml
- application/config/routes.rb
- application/test/controllers/explore_controller_test.rb
Added Repository Explore landing page support.
This is to support adding a landing page for a connector to put generic info and widgets.
> feat: Added Repository Explore landing page support

- application/app/services/repo/repo_url.rb
- application/test/services/repo/repo_url_test.rb
Update RepoUrl to recognize URLs with a HTTP or HTTPS protocol only
Required for #357
> fix: Fixed RepoUrl to recognize URLs with a HTTP or HTTPS protocol only

- application/app/services/repo/resolvers/zenodo_doi_resolver.rb
- application/test/services/repo/resolvers/zenodo_doi_resolver_test.rb
DOIs from Zenodo records resolve to a intermediate redirect like: https://zenodo.org/doi/10.5281/zenodo.16764341
This resolver will check and update to the final Zenodo URL
> feat: Added Zenodo DOI resolver

- application/app/javascript/controllers/modal_controller.js
- application/app/javascript/controllers/utils/link_confirmation_controller.js
- application/app/services/reset_service.rb
- application/app/views/layouts/_modal_delete_confirmation.html.erb
- application/app/views/layouts/nav/_navigation.html.erb
- application/app/views/projects/index.html.erb
- application/app/views/widgets/_reset.html.erb
- application/config/locales/views/en.yml
- application/config/routes.rb
- application/test/services/reset_service_test.rb
- application/test/views/widgets/reset_partial_test.rb
Feature to delete all application metadata and allow for a fresh start.
This is in case there are new changes that are not backwards compatible and users are required to clean up existing data to allow for the new code to work correctly
Fixes #422
> feat: Added reset feature to delete all application metadata

- application/app/helpers/status_helper.rb
- application/app/models/download_file.rb
- application/test/helpers/status_helper_test.rb
PR to fix the logic to determine if the download file can be re-tried.
> fix: Fixed retry check for Download files

- Makefile
- README.md
- docker-compose.yml
- docker/docker-local-override.yaml
- docs/guide/content/development_guide/contributing.md
- docs/guide/content/development_guide/index.md
- docs/guide/content/development_guide/local_environment.md
Created Docker compose configuration to allow running the application locally without imposing the development configuration. This might be required by other installations while they test their own configuration
> feat: Added support to run OnDemand Loop without local configuration

- application/app/process/script_launcher.rb
- application/test/process/script_launcher_test.rb
In production, the logs for the detached process go to the detached process standard output that goes into its log file.
This will cause the file to grow indefinitely.
This fix will create a filename that is different each week, mitigating this issue.
> Detached process log file

- application/app/controllers/file_browser_controller.rb
- application/app/helpers/file_browser_helper.rb
- application/app/views/file_browser/_browser.html.erb
- application/test/controllers/file_browser_controller_test.rb
- application/test/helpers/file_browser_helper_test.rb
- Fixes to file browser for missing or invalid files.
- Added icon to navigate to root folder
- Removed `.. (Parent Directory) `link when in root
Fixes #498
> fix: Fixed error for missing or invalid files

- application/app/controllers/download_files_controller.rb
- application/app/controllers/upload_files_controller.rb
- application/app/models/event.rb
- application/app/views/download_status/_files.html.erb
- application/app/views/projects/show/_download_files.html.erb
- application/app/views/projects/show/_upload_files.html.erb
- application/app/views/upload_status/_files.html.erb
- application/config/locales/controllers/en.yml
- application/config/locales/events/en.yml
- application/config/locales/views/en.yml
- application/config/routes.rb
- application/test/controllers/download_files_controller_test.rb
- application/test/controllers/upload_files_controller_test.rb
- application/test/models/event_test.rb
Added support to retry cancelled or error uploads.
UploadFile is update with the status of pending.
Works in the same way as downloading.
Fixes #510
> feat: Added support to retry cancelled or error uploads
