IQSS/ondemand-loop

- application/app/services/common/http_client.rb
- application/app/services/dataverse/dataverse_service.rb
- application/app/services/dataverse/external_tool_service.rb
Make services use HttpClient class
> Http client refactor

- application/test/services/dataverse/external_tool_service_test.rb
- application/test/utils/http_mock.rb
This test got broken after the last refactor on HttpClient class. Here I create a new mock class and I fix that test
> fix External Tool test

- application/app/views/dataverse/datasets/_breadcrumbs.html.erb
- application/app/views/dataverse/dataverses/_breadcrumbs.html.erb
- application/app/views/dataverse/dataverses/_dataset_item.html.erb
- application/app/views/dataverse/dataverses/_dataverse_item.html.erb
- application/app/views/dataverse/dataverses/_installation.html.erb
- open the links on the same page
- add title to breadcrumbs
> enhance breadcrumbs links

- application/app/assets/stylesheets/custom_styles.scss
- application/app/assets/stylesheets/project_progress.scss
- application/app/controllers/application_controller.rb
- application/app/controllers/projects_controller.rb
- application/app/lib/date_time_common.rb
- application/app/lib/logging_common.rb
- application/app/models/project.rb
- application/app/services/dataverse/connector_download_processor.rb
- application/app/services/dataverse/hub_registry.rb
- application/app/views/layouts/application.html.erb
- application/app/views/projects/_project_header.html.erb
- application/app/views/shared/_file_row_date.html.erb
- application/app/views/shared/_project_bar.html.erb
- application/test/controllers/projects_controller_test.rb
- application/test/lib/loggin_common_test.rb
- application/test/models/project_test.rb
- application/test/services/dataverse/connector_download_processor_test.rb
PR to add the active project summary bar to the top of the page so that it shows in all pages:
> Add active project top bar feature

- application/app/services/detached_process.rb
- application/test/services/detached_process_test.rb
Added missing start statement and unit test
> Added missing start call to start method for CommandServer

- application/app/assets/stylesheets/downloads.scss
- application/app/assets/stylesheets/progress_bar.scss
- application/app/connectors/dataverse/actions/collection_select.rb
- application/app/connectors/dataverse/actions/connector_edit.rb
- application/app/connectors/dataverse/actions/dataset_create.rb
- application/app/connectors/dataverse/actions/dataset_form_tabs.rb
- application/app/connectors/dataverse/actions/dataset_select.rb
- application/app/connectors/dataverse/upload_collection_connector_processor.rb
- application/app/javascript/controllers/list_filter_controller.js
- application/app/views/connectors/dataverse/_collection_select_form.html.erb
- application/app/views/connectors/dataverse/_dataset_form_tabs.html.erb
- application/app/views/connectors/dataverse/_dataset_select_form.html.erb
- application/app/views/connectors/dataverse/_upload_collection_bar.html.erb
- application/config/locales/connectors/en.yml
- application/config/locales/views/en.yml
PR to add support for Collection Selection, Dataset Selection and Dataset Creation.
When creating a UploadBatch, we can use:
- Dataverse URL
- Dataverse Collection URL
- Dataverse Dataset URL
> Added support to select collections and select/create dataset

- .github/workflows/release.yml
> Fixed Make target for release

- application/app/helpers/application_helper.rb
- application/app/helpers/connector_helper.rb
- application/app/views/download_status/_actions.html.erb
- application/app/views/download_status/_files.html.erb
- application/app/views/download_status/index.html.erb
- application/app/views/layouts/_footer.html.erb
- application/app/views/layouts/application.html.erb
- application/app/views/layouts/nav/_logo.html.erb
- application/app/views/layouts/nav/_navigation.html.erb
- application/app/views/projects/_download_files.html.erb
- application/app/views/projects/show/_download_files.html.erb
- application/app/views/projects/show/_upload_files.html.erb
- application/app/views/shared/_file_row_date.html.erb
- application/app/views/shared/_progress_bar.html.erb
- application/app/views/upload_status/_files.html.erb
- application/config/locales/shared/en.yml
- application/config/locales/views/en.yml
Implements most of the accessibility criteria on https://github.com/IQSS/ondemand-loop/issues/149
> Accessibility for dowloads page

- application/app/views/download_status/_actions.html.erb
- application/app/views/download_status/_files.html.erb
- application/app/views/download_status/index.html.erb
- application/app/views/shared/_files_process_header.html.erb
- application/app/views/shared/_progress_bar.html.erb
- application/app/views/shared/_repo_badge.html.erb
- application/app/views/upload_status/_actions.html.erb
- application/app/views/upload_status/_files.html.erb
- application/app/views/upload_status/index.html.erb
- application/config/locales/views/en.yml
fixes: https://github.com/IQSS/ondemand-loop/issues/150
> Accessibility uploads page

- application/app/helpers/dataverse/dataverses_helper.rb
- application/app/views/dataverse/collections/_breadcrumbs.html.erb
- application/app/views/dataverse/collections/_collection_info.html.erb
- application/app/views/dataverse/collections/_dataset_item.html.erb
- application/app/views/dataverse/collections/_dataverse_item.html.erb
- application/app/views/dataverse/collections/_item.html.erb
- application/app/views/dataverse/collections/_search_items.html.erb
- application/app/views/dataverse/collections/show.html.erb
- application/config/locales/shared/en.yml
- application/config/locales/views/en.yml
fixes: https://github.com/IQSS/ondemand-loop/issues/152
> Accessibility for dataverse collections page

- application/app/controllers/sitemap_controller.rb
- application/app/views/layouts/_footer.html.erb
- application/app/views/sitemap/index.html.erb
- application/config/locales/views/en.yml
- application/config/routes.rb
- application/test/controllers/sitemap_controller_test.rb
fixes: https://github.com/IQSS/ondemand-loop/issues/168
depends on: https://github.com/IQSS/ondemand-loop/pull/207
> feat: Sitemap to implement multiple ways criterion

- application/app/controllers/download_files_controller.rb
- application/app/controllers/upload_files_controller.rb
- application/test/controllers/download_files_controller_test.rb
- application/test/controllers/upload_files_controller_test.rb
Added check to stop files from being deleted when they are being downloaded or uploaded
Fixes: #90
> feat: Added restrictions to block deletes for file

- application/app/controllers/dataverse/collections_controller.rb
- application/app/controllers/dataverse/landing_page_controller.rb
- application/app/helpers/dataverse/collections_helper.rb
- application/app/helpers/dataverse/landing_page_helper.rb
- application/app/lib/acts_as_page.rb
- application/app/models/page.rb
- application/app/services/dataverse/collection_service.rb
- application/app/services/dataverse/search_collection_items_url_builder.rb
- application/app/views/dataverse/collections/_search_items.html.erb
- application/app/views/dataverse/landing_page/_installation_items.html.erb
- application/config/locales/connectors/dataverse/en.yml
- application/test/controllers/dataverse/collections_controller_test.rb
- application/test/controllers/dataverse/landing_page_controller_test.rb
- application/test/helpers/dataverse/collections_helper_test.rb
- application/test/helpers/dataverse/landing_page_helper_test.rb
- application/test/services/dataverse/search_collection_items_url_builder_test.rb
fixes: https://github.com/IQSS/ondemand-loop/issues/85
> feat: Dataverse landing and collection view search filter

- application/app/controllers/dataverse/datasets_controller.rb
- application/config/configuration_singleton.rb
- application/test/controllers/dataverse/datasets_controller_test.rb
fixes: https://github.com/IQSS/ondemand-loop/issues/239
> fix: redirect bug on dataset view when referrer is external

- application/app/connectors/dataverse/upload_connector_processor.rb
- application/app/connectors/zenodo/upload_connector_processor.rb
- application/app/models/dataverse/upload_file_response.rb
- application/app/services/upload/multipart_http_ruby_uploader.rb
- application/config/locales/connectors/dataverse/en.yml
- application/test/connectors/dataverse/upload_connector_processor_test.rb
- application/test/fixtures/dataverse/upload_file_response/valid_response.json
- application/test/models/dataverse/upload_file_response_test.rb
- application/test/services/upload/multipart_http_ruby_uploader_test.rb
fixes: https://github.com/IQSS/ondemand-loop/issues/98
> feat: Add MD5 check for Dataverse upload

- application/config/configuration_singleton.rb
- docs/guide/content/admin.md
- docs/guide/content/assets/guide.css
- docs/guide/mkdocs.yml
fixes: https://github.com/IQSS/ondemand-loop/issues/257
> feat: Add Admin Guide to documentation

- docs/guide/content/development_guide/index.md
- docs/guide/content/user_guide/exploring_remote_repositories.md
- docs/guide/content/user_guide/finding_data.md
- docs/guide/mkdocs.yml
Implementation of the Browsing Remote Repositories sections from #242
> feat: Improvements to the user guide => Finding Data section

- application/app/services/repo/resolvers/dataverse_resolver.rb
- application/app/views/connectors/dataverse/_upload_bundle_actions_bar.html.erb
- application/app/views/connectors/dataverse/_upload_bundle_info_bar.html.erb
- application/app/views/connectors/zenodo/_upload_bundle_actions_bar.html.erb
- application/app/views/connectors/zenodo/_upload_bundle_info_bar.html.erb
- application/app/views/dataverse/collections/_breadcrumbs.html.erb
- application/app/views/dataverse/datasets/_breadcrumbs.html.erb
- application/app/views/dataverse/landing_page/index.html.erb
- application/app/views/layouts/_repo_resolver_bar.html.erb
- application/app/views/zenodo/landing_page/index.html.erb
- application/config/locales/connectors/dataverse/en.yml
- application/config/locales/connectors/zenodo/en.yml
- Improvements to the dataverse and zenodo bundle links
- Added consistency to the Zenodo and Dataverse landing pages
- Added logging to failed URL resolution for Dataverse API
> feat: UI Improvements after visual review of the application

- application/app/views/layouts/nav/_navigation.html.erb
- application/app/views/sitemap/index.html.erb
> fix: Fixed sitemap URL in navigation

- Makefile
- README.md
- application/manifest.yml
- docs/guide/content/development_guide/local_environment.md
- docs/guide/content/development_guide/ood.md
- docs/guide/content/installation.md
- docs/guide/overrides/partials/next_prev_links.html
- tools/make/ood_versions.mk
> fix: Updated development guide to show how to use different ood versions

- docs/guide/content/admin.md
- docs/guide/content/development_guide/connectors.md
- docs/guide/content/index.md
- docs/guide/content/user_guide/downloading_files.md
- docs/guide/content/user_guide/finding_data.md
- docs/guide/content/user_guide/index.md
- docs/guide/content/user_guide/projects.md
- docs/guide/content/user_guide/supported_repositories.md
- docs/guide/content/user_guide/uploading_files.md
Some quick feedback on docs, which are great overall!
I left comments on various lines.
> doc fixes, suggestions, and ideas

- docs/guide/content/admin.md
- docs/guide/content/development_guide/local_environment.md
- docs/guide/content/user_guide/downloading_files.md
- docs/guide/content/user_guide/finding_data.md
- docs/guide/content/user_guide/index.md
- docs/guide/content/user_guide/projects.md
- docs/guide/content/user_guide/supported_repositories.md
- docs/guide/content/user_guide/upload_file_selector.md
- docs/guide/content/user_guide/uploading_files.md
Review all the documentation again to enhance it.
Document new feature on dataset draft and old versions browsing.
Fixes: https://github.com/IQSS/ondemand-loop/issues/319
Also related to https://github.com/IQSS/ondemand-loop/issues/242 
- Minor fixes in all guides
- Document pending features
- Document logs location in development guide
> fix: Doc guides second review

- application/app/controllers/dataverse/dataset_versions_controller.rb
- application/app/controllers/dataverse/datasets_controller.rb
- application/app/controllers/projects_controller.rb
- application/app/controllers/upload_bundles_controller.rb
- application/app/helpers/projects_helper.rb
- application/app/javascript/controllers/lazy_loader_controller.js
- application/app/javascript/controllers/submit_button_controller.js
- application/app/services/dataverse/api_service.rb
- application/app/services/dataverse/dataverse_url.rb
- application/app/views/dataverse/datasets/_dataset_actions.html.erb
- application/app/views/dataverse/datasets/_dataset_info.html.erb
- application/app/views/layouts/_repo_resolver_bar.html.erb
- application/app/views/projects/index/_project_header.html.erb
- application/app/views/projects/show/_download_actions.html.erb
- application/app/views/projects/show/_download_files.html.erb
- application/app/views/projects/show/_project_actions.html.erb
- application/app/views/projects/show/_upload_actions.html.erb
- application/config/locales/connectors/dataverse/controllers/en.yml
- application/config/locales/shared/en.yml
- application/config/locales/views/en.yml
- application/test/controllers/dataverse/dataset_versions_controllers_test.rb
- docker-compose.yml
- docs/guide/content/admin.md
- docs/guide/content/development_guide/architecture.md
- docs/guide/content/development_guide/connectors.md
- docs/guide/content/installation.md
- docs/guide/content/user_guide/projects.md
Fixes and improvements while preparing for release 2 to Production.
Error handling improvements
Added project name edit to project detail page
Added active project functionality to project detail page
Added "Add Files" to Download Tab in project detail page
Added unit test for DatasetVersionsController
> Improvements after testing for release 2

- application/app/connectors/dataverse/actions/upload_bundle_create.rb
- application/app/helpers/zenodo/records_helper.rb
- application/app/services/common/http_client.rb
- application/app/services/zenodo/api_service.rb
- application/app/services/zenodo/concerns/zenodo_url_builder.rb
- application/app/views/zenodo/records/_record_actions.html.erb
- application/config/configuration_singleton.rb
- application/config/locales/connectors/dataverse/en.yml
- application/config/locales/connectors/zenodo/en.yml
- application/test/connectors/dataverse/actions/upload_bundle_create_test.rb
- application/test/connectors/zenodo/upload_bundle_connector_metadata_test.rb
- application/test/services/zenodo/concerns/zenodo_url_builder_test.rb
- docs/guide/content/admin.md
Bug Fixes while doing a backend review
Detail of the bugs in the issue
Fixes #336
> fix: Bug fixes found while doing a backend review

- application/app/helpers/dataverse/datasets_helper.rb
- application/app/models/dataverse/dataset_version_response.rb
- application/app/models/dataverse/search_response.rb
- application/app/views/connectors/dataverse/_dataset_select_form.html.erb
Added support to select :draft datasets on Upload Bundle creation
> feat: Added support to select :draft datasets on Upload Bundle creation

- application/app/connectors/dataverse/actions/collection_select.rb
- application/app/connectors/dataverse/actions/connector_edit.rb
- application/app/connectors/dataverse/actions/dataset_create.rb
- application/app/connectors/dataverse/actions/dataset_form_tabs.rb
- application/app/connectors/dataverse/actions/dataset_select.rb
- application/app/connectors/dataverse/actions/upload_bundle_create.rb
- application/app/connectors/zenodo/actions/connector_edit.rb
- application/app/connectors/zenodo/actions/deposition_fetch.rb
- application/app/connectors/zenodo/actions/landing.rb
- application/app/connectors/zenodo/actions/records.rb
- application/app/connectors/zenodo/actions/upload_bundle_create.rb
- application/app/services/command/command_client.rb
- application/test/connectors/dataverse/actions/collection_select_test.rb
- application/test/connectors/dataverse/actions/dataset_form_tabs_test.rb
Improve logging
- Added logging statements
> feat: Improve logging of core features

- application/test/connectors/dataverse/actions/collection_select_test.rb
- application/test/connectors/dataverse/actions/dataset_select_test.rb
- application/test/connectors/dataverse/upload_connector_processor_test.rb
- application/test/connectors/zenodo/actions/depositions_test.rb
- application/test/connectors/zenodo/actions/landing_test.rb
- application/test/connectors/zenodo/actions/records_test.rb
- application/test/helpers/dataverse/datasets_helper_test.rb
- application/test/helpers/zenodo/explore_helper_test.rb
- application/test/helpers/zenodo/records_helper_test.rb
- application/test/models/zenodo/search_response_test.rb
- application/test/services/dataverse/collection_service_test.rb
> fix: Test coverage improvements

- application/app/connectors/connector_action_dispatcher.rb
- application/app/connectors/zenodo/explore_connector_processor.rb
- application/app/connectors/zenodo/explorers/depositions.rb
- application/app/connectors/zenodo/explorers/landing.rb
- application/app/connectors/zenodo/explorers/records.rb
- application/test/connectors/connector_action_dispatcher_test.rb
- application/test/connectors/zenodo/explore_connector_processor_test.rb
- application/test/connectors/zenodo/explorers/depositions_test.rb
- application/test/connectors/zenodo/explorers/landing_test.rb
- application/test/connectors/zenodo/explorers/records_test.rb
- application/test/controllers/explore_controller_test.rb
Added connectors explorers abstraction.
This will enable a simple integration for connectors without having to create controllers and routes
General Improvement after review.
> feat: Added connector explorers abstraction

- application/app/connectors/zenodo/actions/deposition_fetch.rb
- application/app/connectors/zenodo/actions/upload_bundle_create.rb
- application/app/connectors/zenodo/explore_connector_processor.rb
- application/app/helpers/explore_helper.rb
- application/app/helpers/zenodo/landing_helper.rb
- application/app/services/common/http_client.rb
- application/app/views/connectors/dataverse/_upload_bundle_actions_bar.html.erb
- application/app/views/connectors/zenodo/_upload_bundle_actions_bar.html.erb
- application/app/views/connectors/zenodo/depositions/show.html.erb
- application/app/views/connectors/zenodo/landing/index.html.erb
- application/app/views/connectors/zenodo/records/show.html.erb
- application/app/views/layouts/nav/_navigation.html.erb
- application/config/locales/connectors/zenodo/en.yml
- application/test/connectors/zenodo/explore_connector_processor_test.rb
- application/test/helpers/zenodo/landing_helper_test.rb
Refactoring and fixes after local review and testing of the Zenodo explore actions
> fix: refactoring Zenodo explore actions after review and testing

- application/Gemfile
- application/Gemfile.lock
- application/app/controllers/download_files_controller.rb
- application/app/controllers/file_browser_controller.rb
- application/config/i18n-tasks.yml
- application/config/locales/connectors/dataverse/en.yml
- application/config/locales/connectors/zenodo/en.yml
- application/config/locales/controllers/en.yml
- application/config/locales/views/en.yml
- scripts/loop_test.sh
Add i18n tasks validation that runs automatically with tests
Improving testing
> feat: Add i18n tasks validation

- application/app/services/repo/resolvers/doi_resolver.rb
- application/test/services/repo/resolvers/doi_resolver_test.rb
Preparation to add a new resolver to check Domains
Required for #357
> DoiResolver - Added check for already resolved URL

- application/test/services/repo/resolvers/cache_resolver_test.rb
- application/test/services/repo/resolvers/dataverse_resolver_test.rb
- application/test/services/repo/resolvers/domain_resolver_test.rb
- application/test/services/repo/resolvers/zenodo_doi_resolver_test.rb
- application/test/services/repo/resolvers/zenodo_resolver_test.rb
Improving RepoResolvers test coverage
> Improving RepoResolvers test coverage

- application/config/initializers/locale.rb
- docs/guide/content/development_guide/languages_and_translations.md
- docs/guide/mkdocs.yml
Guide improvements - Add translations section to the development guide
> feat: Add translations section to the development guide

- application/app/services/common/file_sorter.rb
- application/test/services/common/file_sorter_test.rb
Improvements to Download and Upload file sorting
Fixes #322
> fix: Improvements to Download and Upload file sorting

- application/app/assets/stylesheets/projects.scss
- application/app/controllers/upload_bundles_connector_controller.rb
- application/app/controllers/upload_bundles_controller.rb
- application/app/javascript/controllers/upload_bundle_name_controller.js
- application/app/views/connectors/dataverse/_collection_select_form.html.erb
- application/app/views/connectors/dataverse/_connector_edit_form.html.erb
- application/app/views/connectors/dataverse/_dataset_create_form.html.erb
- application/app/views/connectors/dataverse/_dataset_select_form.html.erb
- application/app/views/connectors/dataverse/_upload_bundle_actions_bar.html.erb
- application/app/views/connectors/dataverse/collections/_collection_actions.html.erb
- application/app/views/connectors/dataverse/datasets/_dataset_actions.html.erb
- application/app/views/connectors/zenodo/_connector_edit_form.html.erb
- application/app/views/connectors/zenodo/_dataset_select_form.html.erb
- application/app/views/connectors/zenodo/_deposition_create_form.html.erb
- application/app/views/connectors/zenodo/_upload_bundle_actions_bar.html.erb
- application/app/views/connectors/zenodo/shared/_zenodo_record_actions.html.erb
- application/app/views/projects/show/_project_actions.html.erb
- application/app/views/projects/show/_upload_actions.html.erb
- application/config/locales/controllers/en.yml
- application/config/locales/shared/en.yml
- application/config/locales/views/en.yml
- application/config/routes.rb
- application/test/controllers/upload_bundles_connector_controller_test.rb
- application/test/controllers/upload_bundles_controller_test.rb
- application/test/views/projects/upload_actions_view_test.rb
- docs/guide/content/user_guide/uploading_files.md
Added support to update Upload Bundle name
> feat: Added support to update Upload Bundle name

- application/app/connectors/dataverse/handlers/upload_bundle_create.rb
- application/app/connectors/zenodo/handlers/upload_bundle_create.rb
- application/test/connectors/dataverse/handlers/upload_bundle_create_test.rb
- application/test/connectors/zenodo/handlers/upload_bundle_create_test.rb
Updated UploadBundle default name to full repo domain.
To improve UI
> feat: Updated UploadBundle default name to full repo domain

- application/app/assets/stylesheets/application.bootstrap.scss
- application/app/assets/stylesheets/utils.scss
- application/app/controllers/projects_controller.rb
- application/app/views/widgets/_events.html.erb
- application/config/locales/events/en.yml
- application/config/locales/views/en.yml
- application/test/controllers/projects_controller_test.rb
Brief description of what this PR accomplishes.
relates to #396
- List key changes
- Include any breaking changes
> feat: Improvements to the events modal UI

- application/app/connectors/dataverse/download_connector_metadata.rb
- application/app/connectors/zenodo/download_connector_metadata.rb
- application/app/helpers/projects_helper.rb
- application/app/services/dataverse/project_service.rb
- application/app/services/repo/repo_activity_service.rb
- application/app/services/zenodo/project_service.rb
- application/app/views/projects/show/_download_actions.html.erb
- application/app/views/projects/show/_download_files.html.erb
- application/app/views/widgets/_repository_activity.html.erb
- application/config/locales/views/en.yml
- application/test/connectors/dataverse/download_connector_metadata_test.rb
- application/test/connectors/zenodo/download_connector_metadata_test.rb
- application/test/helpers/projects_helper_test.rb
- application/test/services/dataverse/project_service_test.rb
- application/test/services/repo/repo_activity_service_test.rb
- application/test/services/zenodo/project_service_test.rb
- application/test/views/widgets/repository_activity_view_test.rb
Brief description of what this PR accomplishes.
Fixes #[issue-number]
- List key changes
- Include any breaking changes
> feat: Added repository history to Project Downloads tab

- application/app/controllers/concerns/connector_resolver.rb
- application/config/locales/controllers/en.yml
- application/test/controllers/concerns/connector_resolver_test.rb
- application/test/controllers/explore_controller_test.rb
Brief description of what this PR accomplishes.
Fixes #[issue-number]
- List key changes
- Include any breaking changes
> fix: ConnectorResolver error handling fixes

- application/app/assets/stylesheets/utils.scss
- application/app/controllers/concerns/redirect_back_with_anchor.rb
- application/app/javascript/controllers/modal_controller.js
- application/app/views/projects/show/_download_actions.html.erb
- application/app/views/projects/show/_project_actions.html.erb
- application/app/views/shared/_file_row_date.html.erb
- application/app/views/widgets/_events.html.erb
- application/app/views/widgets/_upload_bundle_create.html.erb
- application/app/views/widgets/_upload_bundle_new.html.erb
- application/config/locales/views/en.yml
- application/test/controllers/concerns/redirect_back_with_anchor_test.rb
Add support to select recently used repositories when creating an upload bundle
Fixes #400
> feat: Add recent repositories to Upload Bundle creation

- docs/guide/content/user_guide/downloading_files.md
- docs/guide/content/user_guide/projects.md
- docs/guide/content/user_guide/uploading_files.md
Document in the user guide the events feature
Fixes https://github.com/IQSS/ondemand-loop/issues/428
- Update user guide
> feat: document events in the User Guide

- application/app/views/file_browser/_browser.html.erb
- application/app/views/layouts/_project_bar.html.erb
- application/app/views/projects/index/_project_header.html.erb
- application/app/views/projects/show/_download_actions.html.erb
- application/app/views/projects/show/_project_actions.html.erb
- application/app/views/projects/show/_upload_actions.html.erb
- application/app/views/shared/_ajax_load.html.erb
- application/app/views/shared/_update_inline_field_form.html.erb
Fixed missing button type causing involuntary form submit
Fixes #472
> fix: Fixed missing button type causing involuntary form submit

- application/Gemfile
- application/Gemfile.lock
- application/test/application_system_test_case.rb
Removed unused selenium libs and setup. We are using Cypress
> fix: Removed unused selenium libs and setup. We are using Cypress

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/release.md
- .github/pull_request_template.md
Improvements to the GH issue templates
> fix: improvements to the GitHub templates after review
